version: '3.2'

services:
  letsencrypt-nginx:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      DHPARAM_GENERATION: "false"
      DEFAULT_EMAIL: chaos@owlgaming.net
    volumes:
      - nginx_certs:/etc/nginx/certs
      - nginx_vhosts:/etc/nginx/vhost.d
      - nginx_challenge:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - nginx_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  nginx:
    image: jwilder/nginx-proxy
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_certs:/etc/nginx/certs
      - nginx_vhosts:/etc/nginx/vhost.d
      - nginx_challenge:/usr/share/nginx/html
      - /home/bdm642/nginx/conf.d/cloudflare.conf:/etc/nginx/conf.d/cloudflare.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  nginx_network:
    driver: overlay
    attachable: true

volumes:
  nginx_certs:
  nginx_vhosts:
  nginx_challenge: