name: Docker Image CI

on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
    tags:
      - '**'
    paths-ignore:
      - 'documents/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy a docker image
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        # Everything after the very last slash / for a valid tag
        docker build . --tag braunson/cmpt371:${GITHUB_REF##*/} --tag braunson/cmpt371:latest
        echo ${DOCKER_PASSWORD} | docker login --username braunson --password-stdin
        docker push braunson/cmpt371:${GITHUB_REF##*/}
        docker push braunson/cmpt371:latest

    - name: Deploy to server (test)
      if: github.ref == 'refs/heads/master' || contains(github.ref, 'tags/')
      env:
        ENDPOINT: ${{ secrets.DEV_ENDPOINT }}
      run: curl -X POST $ENDPOINT
    - name: Deploy to server (dev)
      if: github.ref == 'refs/heads/develop'
      env:
        ENDPOINT: ${{ secrets.TEST_ENDPOINT }}
      run: curl -X POST $ENDPOINT
