name: React Project

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
    paths-ignore:
      - 'documents/**'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, lint, build, and test
      if: matrix.os != 'windows-latest'
      run: |
        npm install
        npm run lint
        npm run build
        npm run test
      env:
        CI: true
    # Use the winter!
    - name: npm install, wint, build, and test
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        npm install
        npm run wint
        npm run build
        set CI=true&&npm run test
      env:
        CI: true
