on:
  push:
    branches:
      - '**'
    tags:
      - '**'
    paths-ignore:
      - 'documents/**'
  pull_request:
    types: [opened, reopened]
    paths-ignore:
      - 'documents/**'

name: Static Analysis
jobs:
  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install deps
      run: npm install
    - name: Create coverage report
      run: |
        npm run test:ci
        # Fix paths
        sed -i 's+/home/runner/work/term-project-fall2019-team-2/term-project-fall2019-team-2/+/github/workspace/+g' coverage/lcov.info
      env:
        CI: true
    - name: SonarCloud Scan (Push)
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
