on: [push, pull_request]
name: Static Analysis
jobs:
  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install deps
      run: npm install
    - name: SonarCloud Scan (PR)
      uses: sonarsource/sonarcloud-github-action@master
      if: ${{ github.event_name == 'pull_request' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    # This needs to be separated so they do not run twice.
    - name: SonarCloud Scan (Push)
      uses: sonarsource/sonarcloud-github-action@master
      if: ${{ github.event_name == 'push' && !github.base_ref }} # Base_ref is only set if a PR is made.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
