on: [push, pull_request]
name: Static Analysis
jobs:
  sonarCloudTriggerPush:
    name: SonarCloud Trigger (Push)
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.base_ref == ''
    steps:
    - uses: actions/checkout@master
    - name: Install deps
      run: npm install
    - name: SonarCloud Scan (Push)
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  sonarCloudTriggerPR:
    name: SonarCloud Trigger (PR)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@master
    - name: Install deps
      run: npm install
    - name: SonarCloud Scan (PR)
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    # This needs to be separated so they do not run twice.
