on:
  push:
    branches:
      - '**'
    tags:
      - '**'
    paths-ignore:
      - 'documents/**'
  pull_request:
    types: [opened, reopened]
    paths-ignore:
      - 'documents/**'

name: Static Analysis
jobs:
  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install deps
      run: npm install
    - name: SonarCloud Scan (Push)
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
